version: '3.1'

services:

  todolist_db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3306:3306"

  todolist_adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DESIGN: nette
      ADMINER_DEFAULT_SERVER: todolist_db
    ports:
      - "9000:8080"
